### ISSUE TITLE
Plugin does not compile with android@5.0.0

### ISSUE THREAD

**Issue by tripodsan** [floatinghotpot/cordova-httpd#24]
testing with android@5.0.0 results:

```
cordova/platforms/android/src/com/rjfun/cordova/httpd/CorHttpd.java:15: error: package org.apache.http.conn.util does not exist
import org.apache.http.conn.util.InetAddressUtils;
                                ^
/Users/tripod/codez/screens/master/modules/screens-player/cordova/build/android/target/cordova/platforms/android/src/com/rjfun/cordova/httpd/CorHttpd.java:87: error: cannot find symbol
                        if(InetAddressUtils.isIPv4Address(ip)) {
                           ^
  symbol:   variable InetAddressUtils
  location: class CorHttpd
```

**Comment by Vaporexpress** [comment]
Comment this import (InetAddressUtils is deprecated):
` // import org.apache.http.conn.util.InetAddressUtils;`
And replace this line:
`  // if(InetAddressUtils.isIPv4Address(ip)) {`
 with this code:
` if(inetAddress  instanceof Inet4Address) {
    Log.w(LOGTAG, "local IP: "+ ip);
    return ip;
 }`

**Comment by lamuertepeluda** [comment]
Thank you!

You also need
```java
import java.net.Inet4Address;
```

But why has this issue not yet been solved? It looks trivial...
Perhaps I'll make a PR lately

**Comment by tripodsan** [comment]
also see #30
